[package]
name = "threadpool_fractal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"
error-chain = "*"
threadpool = "*"
image = "*"
num_cpus = "1.13.1"
