[package]
name = "curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raytracer_challenge_reference_impl= { path = "../raytracer_challenge_reference_impl" }
plotters = "0.3.4"