[package]
name = "raytracer_lib_std"
version = "0.1.0"
authors = ["bumzack"]
edition = "2018"

[dependencies]
raytracer_lib_no_std = {path =  "../raytracer_lib_no_std"}
image = "*"
math = { path = "../math/" }
