[package]
name = "raytracer"
version = "0.1.0"
authors = ["bumzack"]
edition = "2018"


[dependencies]
# raytracer_lib_no_std = {path =  "../raytracer_lib_no_std"}

#rustacuda = { path = "../../RustaCUDA" }
#rustacuda_derive = { path = "../../RustaCUDA/rustacuda_derive/" }
#rustacuda_core = { path = "../../RustaCUDA/rustacuda_core/" }

raytracer_lib_std = {path =  "../raytracer_lib_std"}
cpu_kernel_raytracer = { path = "../cpu_kernel_raytracer" }

# crossbeam = "*"

