[package]
name = "raytracer_challenge_reference_impl"
version = "0.1.0"
authors = ["bumzack <bumzacktrara@gmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.10.1"
rand = "*"
image = "*"
crossbeam = "*"
crossbeam-channel = "0.5.6"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
